spring:
  profile:
    active:	
    --dev
---
server:
  port: 8021
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client	
eureka:
  client:
    register-with-eureka: false #表示不想注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
